spring:
  application:
    name: env-printer-springboot

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  runtime-env-name: APP_RUNTIME_VALUE
