name: Build Code Quality Pipeline
run-name: ${{ github.ref_name }}.${{ github.run_number }}

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    name: '-'
    runs-on: ubuntu-latest
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/java-build-codequal.yml@main
    permissions:
      id-token: write
      contents: write 
      security-events: write
      actions: read


### TODO - Look up Secret Inheritence