name: Build Pipeline
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    name: '-'
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/java-build.yml@main
    secrets:
           aws-access-key-id: ${{ secrets.AWS_GITHUB_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_GITHUB_SECRET_ACCESS_KEY_ID }}
    #       # GH_TOKEN: ${{ secrets.GH_TOKEN }}

### TODO - Look up Secret Inheritence